spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:./h2db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

bezkoder:
  app:
    jwtCookieName: bezkorder
    jwtSecret: bezKorderSecretKey
    jwtExpirationMs: 86400000